### ISSUE TITLE
[bug] No possible parsings: Nearley doesn't work with correct 'moo' lexer

### ISSUE THREAD

**Issue by nukisman** [kach/nearley#339]
Please tell me what I do wrong?

```nearley
@{%
const moo = require('moo');

const lexer = moo.compile({
  abc: 'abc',
});
%}

# Pass your lexer object using the @lexer option:
@lexer lexer

Expr -> %abc
```

For input `abc` it gives error

```
/usr/local/lib/node_modules/nearley/lib/nearley.js:265
            throw err;
            ^

Error: nearley: No possible parsings (@0: 'a').
    at Parser.feed (/usr/local/lib/node_modules/nearley/lib/nearley.js:260:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/nearley/bin/nearley-test.js:81:12)
    ...
```

**Comment by tjvr** [comment]
How are you setting up the parser? I’d guess you’re not using `fromCompiled` :-)

**Comment by nukisman** [comment]
@tjvr 
I use `@lexer` option as described in https://nearley.js.org/docs/tokenizers#lexing-with-moo
Then I run `nearleyc grammar.ne -o grammar.js`
Resulting `grammar.js` is:
```js
// Generated automatically by nearley
// http://github.com/Hardmath123/nearley
(function () {
function id(x) {return x[0]; }

const moo = require('moo');

const lexer = moo.compile({
  abc: 'abc',
});
var grammar = {
    Lexer: lexer,
    ParserRules: [
    {"name": "Expr", "symbols": [(lexer.has("abc") ? {type: "abc"} : abc)]}
]
  , ParserStart: "Expr"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
```
And then I run compiled grammar with  `nearley-test -i "abc" grammar.js`

**Comment by tjvr** [comment]
That’s strange, I can’t spot a problem from what you’ve shown us.

Are you on an older version of nearley or moo perhaps?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sudazzle** [comment]
Do we need to install moo as well or moo is included in nearley?
