### ISSUE TITLE
Error: Unkown macro

### ISSUE THREAD

**Issue by jtenner** [kach/nearley#387]
**Preface**: This might be the following issue at: https://github.com/kach/nearley/issues/318
I found a bug 🐛 where importing from a utility grammar file does not import the macros.

Here is my environment

**os**: Windows 10
**nearleyc**: 2.13.0
**node**: 10.60.0
**npm**: 6.1.0
**yarn**: 1.7.0

Example code that reproduces the issue:

**./src/statements/ShowStatement.ne**
```ne
@include "../util.ne"
@include "../expressions/index.ne"

@{%
  const showStatementTemplate = template.statements(`
    __actor = TARGET;
    __modifiers = LIST;

    if (!__api.isActor(__actor)) {
      throw new Error(__actor + " is not an actor.");
    }
    if (!__api.isModifierList(__modifiers)) {
      throw new Error(__modifiers + " is not a modifier list.");
    }
    __api.showStatement(__actor, __list);
  `);
%}

ShowStatement -> "show" __ Expression _ ":" _ List[Expression, _ "," _] _ ";":? {%
  function(d) {
    return showStatementTemplate({
      TARGET: d[2],
      LIST: d[4]
    })
  }
%}
```

**./src/util.ne**

```ne

@{%
  const list = d => [d[0][0], ...d[1].map(e => e[1][0])];
  const first = d => d[0];
  const types = require("babel-types");
  const template = require("babel-template");
%}

List[Of, Seperator] -> $Of ($Seperator $Of):* {% list %}
StartsWith[Start, Of] -> $Start $Of {% d => d[1][0] %}
EndsWith[Of, End] -> $Of $End {% d => d[0][0] %}
Wrapped[Start, Of, End] -> $Start $Of $End {% d => d[1][0] %}

_ -> [\t\r\n ]:*
__ -> [\t\r\n ]:+
```

Here's the output log of the stack trace.

```
> nearleyc src/index.ne -o src/grammar.js

C:\Users\jtenner\AppData\Roaming\npm\node_modules\nearley\lib\compile.js:278
                throw new Error("Unkown macro: " + token.macrocall + " " + ruleName);
               ^

Error: Unkown macro: List
    at buildMacroCallToken (C:\Users\jtenner\AppData\Roaming\npm\node_modules\nearley\lib\compile.js:278:23)
    at buildToken (C:\Users\jtenner\AppData\Roaming\npm\node_modules\nearley\lib\compile.js:149:24)
    at buildRule (C:\Users\jtenner\AppData\Roaming\npm\node_modules\nearley\lib\compile.js:95:29)
    at produceRules (C:\Users\jtenner\AppData\Roaming\npm\node_modules\nearley\lib\compile.js:84:28)
    at Compile (C:\Users\jtenner\AppData\Roaming\npm\node_modules\nearley\lib\compile.js:73:17)
    at Compile (C:\Users\jtenner\AppData\Roaming\npm\node_modules\nearley\lib\compile.js:53:29)
    at Compile (C:\Users\jtenner\AppData\Roaming\npm\node_modules\nearley\lib\compile.js:53:29)
    at StreamWrapper.<anonymous> (C:\Users\jtenner\AppData\Roaming\npm\node_modules\nearley\bin\nearleyc.js:57:17)
    at StreamWrapper.emit (events.js:187:15)
    at finishMaybe (_stream_writable.js:641:14)
```

**Comment by jtenner** [comment]
I decided to try the fix from #318 and it worked perfectly. It appears my problem is a duplicate.
