### ISSUE TITLE
Basic nearley-railroad example fails on windows

### ISSUE THREAD

**Issue by stuartlong** [kach/nearley#393]
Following the instructions from https://nearley.js.org/ to generate a railroad diagram for a simple grammar fails on Windows. Running `nearley-railroad csscolor.ne -o csscolor.html` on
```ne
# Match a CSS color
# http://www.w3.org/TR/css3-color/#colorunits
@builtin "whitespace.ne" # `_` means arbitrary amount of whitespace
@builtin "number.ne"     # `int`, `decimal`, and `percentage` number primitives
csscolor -> "#" hexdigit hexdigit hexdigit hexdigit hexdigit hexdigit
          | "#" hexdigit hexdigit hexdigit
          | "rgb"  _ "(" _ colnum _ "," _ colnum _ "," _ colnum _ ")"
          | "hsl"  _ "(" _ colnum _ "," _ colnum _ "," _ colnum _ ")"
          | "rgba" _ "(" _ colnum _ "," _ colnum _ "," _ colnum _ "," _ decimal _ ")"
          | "hsla" _ "(" _ colnum _ "," _ colnum _ "," _ colnum _ "," _ decimal _ ")"
hexdigit -> [a-fA-F0-9]
colnum   -> int | percentage
```
results in the following error:
```
Error: invalid syntax at line 1 col 1:

  # Match a CSS color
  ^
Unexpected "#"

    at Parser.feed (C:\Users\stuartlo\AppData\Roaming\npm\node_modules\nearley\lib\nearley.js:317:27)
    at StreamWrapper.write [as _write] (C:\Users\stuartlo\AppData\Roaming\npm\node_modules\nearley\lib\stream.js:14:18)
    at doWrite (_stream_writable.js:397:12)
    at writeOrBuffer (_stream_writable.js:383:5)
    at StreamWrapper.Writable.write (_stream_writable.js:290:11)
    at ReadStream.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at ReadStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
```

Versions:
- node v8.11.3
- npm v5.6.0
- nearley v2.15.0

**Comment by kach** [comment]
Ooh, good catch. Try again, after upgrading to nearley 2.15.1?

**Comment by stuartlong** [comment]
Yup, that fixes it. Thanks!
