### ISSUE TITLE
Documentation error - Tokenisers > Lexing with Moo - example is incorrect

### ISSUE THREAD

**Issue by TheMrZZ** [kach/nearley#405]
In the documentation, this example is given for Lexing with Moo:
```javascript
@{%
const moo = require("moo");

const lexer = moo.compile({
  ws:     /[ \t]+/,
  number: /[0-9]+/,
  word: /[a-z]+/,
  times:  /\*|x/
});
%}

# Pass your lexer object using the @lexer option:
@lexer lexer

# Use %token to match any token of that type instead of "token":
multiplication -> %number %ws %times %ws %number {% ([first, , , , second]) => first * second %}

# Literal strings now match tokens with that text:
trig -> "sin" %number
```

However, a quick test shows us that feeding the string "2 x 8" to a parser using this grammar does not work.

Result is:
```
nearley-test grammar.js -i "2 * 8"
C:\Users\Florian\WebstormProjects\MineScript\src\new-parser\grammar.js:12
  word: /[a-z]+/,
  ^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Florian\AppData\Roaming\npm\node_modules\nearley\bin\nearley-test.js:50:44)
```

Here, the `word` token has priority on the `times` token. This prevents `x` to be catch in the `times` token.

**Comment by tjvr** [comment]
Really good point!

To lex this correctly we'd actually need to use Moo keywords: otherwise `xylophone` would parse as two separate tokens.

Probably we should just simplify this example, to not use `x` at all 🙂

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TheMrZZ** [comment]
Not sure what to you mean here. What should I use as keywords for this example to work?

However yes, simplifying this example might be a good idea.
