### ISSUE TITLE
Grammar does not work when Moo is used - but works without 

### ISSUE THREAD

**Issue by TheMrZZ** [kach/nearley#406]
I'm using the nearley grammar (and parser) with the moo tokeniser. My grammar.ne file is the following:

    @{%
        const moo = require('moo')
        let lexer = moo.compile({
            number: /[0-9]+/
        });
    %}
    
    @lexer lexer
    
    trig -> "sin" [0-9]:+

When parsing the string "sin8" to a parser, via `nearley-test grammar.js -i "sin8"`, I get the following error:

    throw new Error(this.formatError(token, "invalid syntax"))
          ^
    
    Error: invalid syntax at line 1 col 1:
    
      sin8
      ^
        at Lexer.next (C:\Users\Florian\WebstormProjects\MineScript\node_modules\moo\moo.js:397:13)
        at Parser.feed (C:\Users\Florian\AppData\Roaming\npm\node_modules\nearley\lib\nearley.js:270:30)
        at Object.<anonymous> (C:\Users\Florian\AppData\Roaming\npm\node_modules\nearley\bin\nearley-test.js:83:12)
        at Module._compile (module.js:652:30)
        at Object.Module._extensions..js (module.js:663:10)
        at Module.load (module.js:565:32)
        at tryModuleLoad (module.js:505:12)
        at Function.Module._load (module.js:497:3)
        at Function.Module.runMain (module.js:693:10)
        at startup (bootstrap_node.js:191:16)

However, commenting `@lexer lexer` makes it work, and matches the "sin8" string.
This example is taken directly [from the documentation][1] and does not work, so I'm wondering where I am wrong. I know I'm missing something because I can't get Moo to work with Nearley correctly. 

  [1]: https://nearley.js.org/docs/tokenizers#lexing-with-moo

**Comment by tjvr** [comment]
You haven't declared a rule for `sin` in your Tokenizer. 🙂

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TheMrZZ** [comment]
So when using a custom lexer, string literals are equivalent to using the % notation ? Aka %sin is like "sin" ?

**Comment by tjvr** [comment]
Not quite; `"sin"` matches a token with the _value_ `sin`, whereas `%foo` matches a token with the _type_ `foo`.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tjvr** [comment]
```
# Use %token to match any token of that type instead of "token":
multiplication -> %number %ws %times %ws %number {% ([first, , , , second]) => first * second %}

# Literal strings now match tokens with that text:
trig -> "sin" %number
```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Zemnmez** [comment]
I've also been having issues with nearley / moo so I tried to see what is going on with this example.

It was my (now I see incorrect) intuition that the tokeniser would kick in as directed by nearley when a token was specified. For example, as in the example, I expected:

```
main -> "sin" %number
```

To match the literal `"sin"` and then the _token_ `%number`. From what I've got from this post, what `"sin"` means changes when a lexer is used. Instead of meaning a literal string, it means _any token_ that _has the computed value_ `"sin"`. Thus, if a token is not defined for this context the parser will complain.

**Comment by rein-dc** [comment]
Yep I'm also struggling with this confusion. Ended up scrapping the lexer for now just so I could get things going
