### ISSUE TITLE
Tab character regression in Nearley 2.15

### ISSUE THREAD

**Issue by jeromesimeon** [kach/nearley#413]
The most recent versions of Nearly seem to dislike tab characters inside of strings in the grammar.

Here is a minimal example:
```
$ cat teststring.txt 
a	b$ 
$ 
$ cat teststring.ne
rule1 -> "a	b"
$ nearleyc teststring.ne -o teststring.js 
undefined:1
"a	b"
  ^

SyntaxError: Unexpected token 	 in JSON at position 2
    at JSON.parse (<anonymous>)
    at Object.value (~/.nvm/versions/node/v8.12.0/lib/node_modules/nearley/lib/nearley-language-bootstrapped.js:30:26)
    at Lexer.next (~/.nvm/versions/node/v8.12.0/lib/node_modules/nearley/node_modules/moo/moo.js:377:34)
    at Parser.feed (~/.nvm/versions/node/v8.12.0/lib/node_modules/nearley/lib/nearley.js:270:30)
    at StreamWrapper.write [as _write] (~/.nvm/versions/node/v8.12.0/lib/node_modules/nearley/lib/stream.js:14:18)
    at doWrite (_stream_writable.js:396:12)
    at writeOrBuffer (_stream_writable.js:382:5)
    at StreamWrapper.Writable.write (_stream_writable.js:290:11)
    at ReadStream.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
```

As far as I can tell this is a regression (or specification change?) between Nearley 2.13 and Nearley 2.14

A more lengthy trace from local testing here:

```
$ cat teststring.txt | od -An -vtx1
           61  09  62                                                    

$ cat teststring.ne | od -An -vtx1
           72  75  6c  65  31  20  2d  3e  20  22  61  09  62  22  0a    

$ npm install -g nearley@2.13 
+ nearley@2.13.0
removed 1 package and updated 1 package in 5.696s
$ nearleyc teststring.ne -o teststring.js 
$ cat teststring.js 
// Generated automatically by nearley, version 2.13.0
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "rule1$string$1", "symbols": [{"literal":"a"}, {"literal":"\t"}, {"literal":"b"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "rule1", "symbols": ["rule1$string$1"]}
]
  , ParserStart: "rule1"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
$ npm install -g nearley@2.14
+ nearley@2.14.0
added 1 package from 2 contributors and updated 1 package in 1.02s
$ nearleyc teststring.ne -o teststring.js 
undefined:1
"a	b"
  ^

SyntaxError: Unexpected token 	 in JSON at position 2
    at JSON.parse (<anonymous>)
    at Object.value (~/.nvm/versions/node/v8.12.0/lib/node_modules/nearley/lib/nearley-language-bootstrapped.js:30:26)
    at Lexer.next (~/.nvm/versions/node/v8.12.0/lib/node_modules/nearley/node_modules/moo/moo.js:377:34)
    at Parser.feed (~/.nvm/versions/node/v8.12.0/lib/node_modules/nearley/lib/nearley.js:270:30)
    at StreamWrapper.write [as _write] (~/.nvm/versions/node/v8.12.0/lib/node_modules/nearley/lib/stream.js:14:18)
    at doWrite (_stream_writable.js:396:12)
    at writeOrBuffer (_stream_writable.js:382:5)
    at StreamWrapper.Writable.write (_stream_writable.js:290:11)
    at ReadStream.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
$ npm install -g nearley@2.15.1 
+ nearley@2.15.1
updated 1 package in 0.745s
$ nearleyc teststring.ne -o teststring.js 
undefined:1
"a	b"
  ^

SyntaxError: Unexpected token 	 in JSON at position 2
    at JSON.parse (<anonymous>)
    at Object.value (~/.nvm/versions/node/v8.12.0/lib/node_modules/nearley/lib/nearley-language-bootstrapped.js:30:26)
    at Lexer.next (~/.nvm/versions/node/v8.12.0/lib/node_modules/nearley/node_modules/moo/moo.js:377:34)
    at Parser.feed (~/.nvm/versions/node/v8.12.0/lib/node_modules/nearley/lib/nearley.js:270:30)
    at StreamWrapper.write [as _write] (~/.nvm/versions/node/v8.12.0/lib/node_modules/nearley/lib/stream.js:14:18)
    at doWrite (_stream_writable.js:396:12)
    at writeOrBuffer (_stream_writable.js:382:5)
    at StreamWrapper.Writable.write (_stream_writable.js:290:11)
    at ReadStream.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
$ 
```

**Comment by jeromesimeon** [comment]
Additional comment, using `"a\tb"` in the grammar does work.

**Comment by tjvr** [comment]
Interesting. How easily can you replace tab characters with `\t` in the strings in your grammar?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jeromesimeon** [comment]
Very easily! That's what we did in https://github.com/accordproject/cicero/pull/233 :)

**Comment by jeromesimeon** [comment]
So to clarify, I'm perfectly ok if this is considered a feature rather than a bug (i.e., part of the specification for strings) -- The more delicate question is whether there is a specification for strings, and whether that issue might show up for other characters (other kinds of funny whitespace for instance).

**Comment by tjvr** [comment]
Sounds like a bug with the string token, although I've just checked the regex and it looks fine to me 😕

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jeromesimeon** [comment]
I got lost in that part of the code, but I had the impression that before the token reaches that point, it gets parsed using the builtin string parser, which should escape from a tab to `\t` ?

**Comment by jeromesimeon** [comment]
If you meant that regex:
```
    string: {
        match: /"(?:[^\\"\n]|\\["\\/bfnrt]|\\u[a-fA-F0-9]{4})*"/,
        value: x => JSON.parse(x),
        next: 'main',
    },
```
it looks fine to me as well.

**Comment by jeromesimeon** [comment]
Same issue for form feed:
```
bash-3.2$ npm install -g nearley@2.15.1 
+ nearley@2.15.1
added 1 package from 2 contributors and updated 1 package in 0.729s
bash-3.2$ nearleyc teststring.ne -o teststring.js  
undefined:1
"ab"
  ^

SyntaxError: Unexpected token  in JSON at position 2
    at JSON.parse (<anonymous>)
    at Object.value (~/.nvm/versions/node/v8.12.0/lib/node_modules/nearley/lib/nearley-language-bootstrapped.js:30:26)
    at Lexer.next (~/.nvm/versions/node/v8.12.0/lib/node_modules/nearley/node_modules/moo/moo.js:377:34)
    at Parser.feed (~/.nvm/versions/node/v8.12.0/lib/node_modules/nearley/lib/nearley.js:270:30)
    at StreamWrapper.write [as _write] (~/.nvm/versions/node/v8.12.0/lib/node_modules/nearley/lib/stream.js:14:18)
    at doWrite (_stream_writable.js:396:12)
    at writeOrBuffer (_stream_writable.js:382:5)
    at StreamWrapper.Writable.write (_stream_writable.js:290:11)
    at ReadStream.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
bash-3.2$ npm install -g nearley@2.13.0
+ nearley@2.13.0
removed 1 package and updated 1 package in 0.685s
bash-3.2$ nearleyc teststring.ne -o teststring.js
bash-3.2$ 
```

**Comment by tjvr** [comment]
Oh, I see the problem. That regex allows tab characters in strings; it's `JSON.parse` which doesn't.

We should either replace `JSON.parse` with some hand-rolled code for string escapes, or stop the regex from matching tabs/form-feeds (so you get a nice syntax error). The latter would be easier. What do you think?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jeromesimeon** [comment]
I guess I'm happy either way.

I would prefer if the escaping is internal to Nearley which means it's backward compatible with Nearley 2.13.* but I'm fine if it's a nice error instead with something that documents what characters have  to be escaped inside a Nearley string.
