### ISSUE TITLE
nearley-test balks when using @preprocessor typescript

### ISSUE THREAD

**Issue by Zemnmez** [kach/nearley#420]
`nearley-test` expects input in non-typescript form, and will crash if it's fed typescript:
```
function id(d: any[]): any { return d[0]; }
             ^

SyntaxError: Unexpected token :
    at new Script (vm.js:83:7)
    at createScript (vm.js:267:10)
    at Object.runInThisContext (vm.js:319:10)
    at Module._compile (internal/modules/cjs/loader.js:686:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:659:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

There's no way to disable the typescript preprocessor via a flag, so I'm building both the typescript and the vanilla js versions like this:
```bash
nearleyc ./src/grammar.ne -o ./src/grammar.jsx &&
nearleyc <(sed 's/^@preprocessor.*//g' ./src/grammar.ne) -o ./src/grammar.js
```

I do think this should be easier.

**Comment by AlansCodeLog** [comment]
I wanted to try nearley-unparse and also ran into this, but in my case not even manually disabling the typescript pre-processor, stripping any typescript (since just removing `@preprocessor typescript` only changes the code nearley generates), then writing to a `.js` file works because I'm importing helpers from other typescript files.

I would have to first transpile any typescript files the parser imports, or put all the helpers in the grammar then compile parser -> transpile to js -> feed to nearley-unparse, or ditch typescript, write everything in js and type the helpers separately (because they are used by other parts of the program).

**Comment by kulte** [comment]
What are people doing to solve this? I have the same scenario as @AlansCodeLog.

**Comment by AlansCodeLog** [comment]
Project looks pretty dead. I ended up going with chevrotain if it's any help. It was a bit more difficult and it's not a parser generator, but it's very nice, fast, and it's still maintained (not that I ever ran into any issues).
