### ISSUE TITLE
Syntax errors after arbitrary number of repeated items

### ISSUE THREAD

**Issue by andrew-carroll** [kach/nearley#428]
I am using:

Ubuntu 18.04.1 LTS on Windows Subsystem for Linux
Node v8.10.0
npm 3.5.2
nearlyc 2.16.0

I am trying to write a grammar for a file format with very large data files. These data files consist of key-value properties, named and unnamed structs, and arrays. I have hit a snag in a section of a sample file that consists of a very long series of identically-formatted structs. When the length of this series surpasses an arbitrary threshold, Nearley stops parsing tokens correctly.

*Steps to recreate:*

Given a tokenized grammar defined:

```ne
@{%
  const unquote = x => x.slice(1,-1)
  const untilEOL = x => x.split(/\n$/)[0]
  const unindent = x => x.split(/^\t*/)[1]
  const keyName = x => x.split('=')[0]

  const moo = require('moo')
  const lexer = moo.compile({
    file_header: {
      match: /CK2txt\n/,
      lineBreaks: true,
      value: untilEOL
    },
    array: {
      match: /\t*[a-z_]+?=\s*{[\s]*[a-zA-Z0-9._ ]+[\s]*}\n?/,
      lineBreaks: true,
      value: x => {
        return x.split(/^\t*/)[1]
        .split('=')[0]
        + '='
        + x.split(/{\s*/)[1]
        .split(/\s*}/)[0]
        .split(/\s+/)
        .join(',')
      }
    },
    anonStructOpen: {
      match: /[ \t]+\n\t+{\n/,
      lineBreaks: true
    },
    structOpen: {
      match: /[ \t]*[a-zA-Z0-9_]+=\n\t*{\n/,
      lineBreaks: true,
      value: x => unindent(keyName(x))
    },
    structClose: {
      match: /\t*}\n/,
      lineBreaks: true
    },
    key: {
      match: /[ \t]*[a-zA-Z0-9_.]+=/,
      value: x => unindent(keyName(x))
    },
    date: /[1-9]\d*\.\d+\.\d+$/,
    decimal: /-?\d+\.\d+/,
    integer: /-?\d+/,
    string: {
      match: /".*?"[ ]*/,
      value: unquote
    },
    symbol: {
      match: /[a-zA-Z][a-zA-Z_]+$/,
      lineBreaks: true,
      value: untilEOL
    },
    br: {
      match: /\n/,
      lineBreaks: true
    },
    emptyLine: {
      match: /\s*\n/,
      lineBreaks: true
    }
  })
%}

@lexer lexer

CK2txt ->
  %file_header
  item:+
  %structClose
  %key %string

item ->
  prop | struct | %array | %emptyLine

structOpen ->
  %structOpen | %anonStructOpen

struct ->
  structOpen item:+ %structClose

prop ->
  %key primitive %br

primitive ->
  %string | %symbol | %decimal | %integer | %date
```

And [this](https://gist.github.com/andrew-carroll/7b186d1806843af943c5d52e4f1cad2e) sample file to parse, we get the following output:

```
$ nearleyc grammar.ne --out grammar.js
$ cat ./sample.ck2 | nearley-test grammar.js
/c/Users/mrand/Documents/code/ck2reader/node_modules/moo/moo.js:518
      throw new Error(this.formatError(token, "invalid syntax"))
      ^

Error: invalid syntax at line 4590 col 1:

                        s
  ^
    at Lexer._token (/c/Users/mrand/Documents/code/ck2reader/node_modules/moo/moo.js:518:13)
    at Lexer.next (/c/Users/mrand/Documents/code/ck2reader/node_modules/moo/moo.js:465:19)
    at Parser.feed (/usr/local/lib/node_modules/nearley/lib/nearley.js:270:30)
    at StreamWrapper.write [as _write] (/usr/local/lib/node_modules/nearley/lib/stream.js:14:18)
    at doWrite (_stream_writable.js:397:12)
    at writeOrBuffer (_stream_writable.js:383:5)
    at StreamWrapper.Writable.write (_stream_writable.js:290:11)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
```

The part we're looking at in the sample file is the struct of structs beginning at line [1830](https://gist.github.com/andrew-carroll/7b186d1806843af943c5d52e4f1cad2e#file-sample-ck2-L1830), going until the end of the file. As you can see, all of the structs in this struct are identical: I have replaced all the unique structs with one example struct that is verified working, in order to factor out the possibility of idiosyncracies between structs as the cause of this error.

Now, delete lines 4577 through 4591 and run  `nearley-test` again. No error this time! [see gist for output too long to paste here](https://gist.github.com/andrew-carroll/ef713b02f978d991ae1712337d7795b2) Even though there are 183 more of the exact same struct remaining, removing just one makes the whole thing work.

**Comment by AnyhowStep** [comment]
Did you ever find a solution for this?
