### ISSUE TITLE
TypeError: this.rule.postprocess is not a function

### ISSUE THREAD

**Issue by baranskistad** [kach/nearley#441]
I am using node 8.3.0, npm 6.4.1, and nearleyc 2.16.0.

An error seems to be occurring inside of nearley. I ran `nearley-test` with the following grammar
```
@{%
    var line = 1;
    const ep = function(d){
        return {
            type: "expression",
            op: d[2],
            left: d[0],
            right: d[4]
        }
    }
    const cp = function(d){
        var paramslist = []
        for(i in d[4]){
            if(d[4][i] != ","){
                paramslist.push(d[4][i])
            }
        }
        return {
            type: "call",
            name: d[0],
            args: paramslist
        }
    }
    const op = function(d){
        var paramslist = d[2]
        for(i in paramslist){
            if(paramslist[i] == ","){
                paramslist.splice(i);
            }
        }
        return {
            type: "object",
            args: paramslist,
            chunk: d[10]
        }
    }
%}

chunk ->
    _ brick _ {% d => d[1] %}
  | _ brick end newline:? brick {% d => d[1] %}
  | _ brick newline brick {% d => d[1] %}

brick ->
    assignment
  | call
  | object

assignment -> variable _ "=" _ atom {% function(d){ return { type: "assignment", left: d[0], right: d[4][0] } } %}

call -> variable _ "(" _ paramslist:? _ ")" {% d => cp(d) %}

paramslist ->
    paramslist _ "," _ atom {% d => [d[0], d[4]] %}
  | atom {% d => d[0] %}

atom ->
    expression
  | boolean
  | variable
  | string
  | call
  | object

object -> "(" _ paramslist:? _ ")" _ newline:? "{" _ newline:? (chunk:?) _ newline:? "}" {% d => op(d)%}

expression ->
    number newline:? {% function (d) { return { type: "expression", op: false, left: d[0] } } %}
    | expression _ "+" _ expression newline:? {% d => ep(d) %}
    | expression _ "-" _ expression newline:? {% d => ep(d) %}
    | expression _ "*" _ expression newline:? {% d => ep(d) %}
    | expression _ "/" _ expression newline:? {% d => ep(d) %}
    | "(" _ expression _ ")" newline:? {% function(d){ d = d[2]; d.parenthesized = true; return d } %}

number -> "-":? [0-9]:+ ".":? ([0-9]:+):? {% d => d.join("") %}

string -> "\"" [^"]:* "\"" {% function(d){ return { type: "string", token: d[1].join("") } } %}

boolean -> ("true" | "false") {% function(d){ return { type: "boolean", token: d[0].join("") } } %}

variable -> [a-zA-Z]:* {% d =>  d[0].join("") %}

end -> ";"

_ -> " ":?

newline -> "\n" {% line++ %}
```
And it is erroring
```
Barans-Air:nift BaranSkistad$ nearley-test lib/grammar.js
var = "hello"
/usr/local/lib/node_modules/nearley/lib/nearley.js:69
            this.data = this.rule.postprocess(this.data, this.reference, Parser.fail);
                                  ^


TypeError: this.rule.postprocess is not a function
    at State.finish (/usr/local/lib/node_modules/nearley/lib/nearley.js:69:35)
    at Column.process (/usr/local/lib/node_modules/nearley/lib/nearley.js:93:23)
    at Parser.feed (/usr/local/lib/node_modules/nearley/lib/nearley.js:309:24)
    at StreamWrapper.write [as _write] (/usr/local/lib/node_modules/nearley/lib/stream.js:14:18)
    at doWrite (_stream_writable.js:371:12)
    at writeOrBuffer (_stream_writable.js:357:5)
    at StreamWrapper.Writable.write (_stream_writable.js:274:11)
    at ReadStream.ondata (_stream_readable.js:628:20)
    at emitOne (events.js:115:13)
    at ReadStream.emit (events.js:210:7)
```
I can't figure out why this is happening, any help?

**Comment by kach** [comment]
The last line, `newline -> "\n" {% line++ %}`, doesn't have a function as the postprocessor because `line++` evaluates to a number. Switch to `d => line++` or something.

**Comment by baranskistad** [comment]
Of course, the one thing I miss. Sorry for wasting your time!
