### ISSUE TITLE
nuller doesn't actually exist

### ISSUE THREAD

**Issue by takase1121** [kach/nearley#465]
My log:
```C:\Users\Takase\Desktop\Node.js Project\shiro\nearley\test\q5o40n1l.kar:224
    {"name": "nl", "symbols": ["nl$string$1"], "postprocess": nuller},
                                                              ^

ReferenceError: nuller is not defined
    at C:\Users\Takase\Desktop\Node.js Project\shiro\nearley\test\q5o40n1l.kar:224:63
    at Object.<anonymous> (C:\Users\Takase\Desktop\Node.js Project\shiro\nearley\test\q5o40n1l.kar:241:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\Takase\AppData\Roaming\npm\node_modules\nearley\bin\nearley-test.js:24:44)
```

What I did:
```nl -> 
    "\r\n" {% nuller %}
    | "\n" {% nuller %}
    | "\r" {% nuller %}
```

I mean sure I could just define `nuller` on the top of the file, but aren't they supposed to be there?

> nearley provides two built-in postprocessors for the most common scenarios:
> - `id` returns the first element of the data array. This is useful to extract the content of a single-element array: `foo -> bar {% id %}`
> - `nuller` returns the JavaScript `null` value. This is useful for whitespace rules: `space -> " " {% nuller %}`

https://nearley.js.org/docs/grammar

**Comment by kach** [comment]
Yes, this is #97, we need to fix the docs.
