### ISSUE TITLE
Error when using nearley-test

### ISSUE THREAD

**Issue by Nicemanss** [kach/nearley#470]
Hello,

First off, really love what you've done with Nearley! Very amazing how it just parses everything. I'm working on a twitter bot that will allow users to tip each other with cryptocurrency, and it's using Nearley for parsing.

I've got the input file ( https://github.com/Nicemanss/HPBTipBotTwitter/blob/master/src/command.ne ) and it successfully generates an output file ( https://github.com/Nicemanss/HPBTipBotTwitter/blob/master/src/command.ts )

When running the test, I get the following error though:
`➜  src git:(master) ✗ nearley-test -i "help" command.ts
/Users/fredrik/Desktop/HPBTipBotTwitter/src/command.ts:5
function id(d: any[]): any { return d[0]; }
             ^

SyntaxError: Unexpected token :
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)`

Any idea what is the cause of this?

**Comment by slifty** [comment]
I'm not a project maintainer but was curious -- the links to those files are 404 (maybe it's a private repo?) so I wasn't able to take a look.
