### ISSUE TITLE
Error when reporting parsing error

### ISSUE THREAD

**Issue by nick-keller** [kach/nearley#479]
# How to reproduce
I am trying to parse lines with the character `a` with the following grammar:

```nearley
main -> "a" {% (d) => [d[0]] %}
      | main newline "a" {% (d) => [...d[0], d[2]] %}

newline -> "\r" "\n" {% () => null %}
         | "\r" | "\n" {% () => null %}
```

If I parse a string that is valid it works just fine, but as soon as I try to parse something that is not I get the following error:
```
TypeError: Cannot read property '0' of undefined
    at Parser.<anonymous> (.../node_modules/nearley/lib/nearley.js:361:35)
    at Array.forEach (<anonymous>)
    at Parser.reportError (.../node_modules/nearley/lib/nearley.js:360:21)
    at Parser.feed (.../node_modules/nearley/lib/nearley.js:314:42)
```
# Expected behavior
I'd expect to have the standard error: `Error: Syntax error at line 1 col 2: [...]` that allows me to mark the error position.

# Info
Nearley version: `2.19.0`

I've tried to dig into the code but I'm missing some base knowledge here...

**Comment by kach** [comment]
@airportyh Seems like it's an error thrown in Parser.reportError… any ideas? And, relatedly, any progress on #475 ?

As cool as the fancy error reporting is, if it's causing errors then I might temporarily revert to the "old-fashioned" errors until the error reporting is more stable. What do you think?

**Comment by airportyh** [comment]
Okay. I am fine with reverting until we fix it.

**Comment by adematte** [comment]
I think that the new error reporting should be regarded as a breaking change since it will break existing apps parsing the previous error messages. Should be a major version bump and not just a minor one.
