### ISSUE TITLE
Custom Lexer with @import

### ISSUE THREAD

**Issue by LiamRiddell** [kach/nearley#489]
Im trying to use moo with Nearley. Which is going fine until I'm trying to use more than one nearley file. Which keeps throwing the error:

```
nearley.js:173
        var rules = rules.map(function (r) { return (new Rule(r.name, r.symbols, r.postprocess)); });
                          ^

TypeError: rules.map is not a function
    at Function.Grammar.fromCompiled (E:\{hidden}\node_modules\nearley\lib\nearley.js:173:27)
    at Object.<anonymous> (E:\{hidden}\index.js:111:51)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```
If I remove `@lexer ` directive from the top of arithemetic.ne file it breaks. How do you build a robust import structure while using custom lexer

**Main.ne:**
```
@{%
    const moo = require("moo");

    const lexer = moo.compile({
        ws:      /[ \t]+/,
        decimal: /(?:^\+|\-?)(?:[1-9]\d{0,4}|0|)\.\d/,
        integer: /(?:[+-]?)(?:\d+)/,
        lparen:  '(',
        rparen:  ')',
        multiplication: ['times', '*', 'multiply'],
        nl: { match: /\n/, lineBreaks: true }
    });
%}

# Pass your lexer object using the @lexer option:
@lexer lexer

# Include other grammars
@include "./arithmetic.ne"`
```

**Arithmetic.ne**
```
# ########################################
# Test import
# ########################################
@lexer lexer

# Use %token to match any token of that type instead of "token":
multiplication -> %integer %ws %multiplication %ws %integer {% ([first, , , , second]) => parseInt(first) * parseInt(second) %}
                | %decimal %ws %multiplication %ws %decimal {% ([first, , , , second]) => parseFloat(first) * parseFloat(second) %}
```

**Compiled Grammar:**
```
// Generated automatically by nearley, version 2.19.0
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }

    const moo = require("moo");

    const lexer = moo.compile({
        ws:      /[ \t]+/,
        decimal: /(?:^\+|\-?)(?:[1-9]\d{0,4}|0|)\.\d/,
        integer: /(?:[+-]?)(?:\d+)/,
        lparen:  '(',
        rparen:  ')',
        multiplication: ['times', '*', 'multiply'],
        nl: { match: /\n/, lineBreaks: true }
    });
var grammar = {
    Lexer: lexer,
    ParserRules: [
    {"name": "multiplication", "symbols": [(lexer.has("integer") ? {type: "integer"} : integer), (lexer.has("ws") ? {type: "ws"} : ws), (lexer.has("multiplication") ? {type: "multiplication"} : multiplication), (lexer.has("ws") ? {type: "ws"} : ws), (lexer.has("integer") ? {type: "integer"} : integer)], "postprocess": ([first, , , , second]) => parseInt(first) * parseInt(second)},
    {"name": "multiplication", "symbols": [(lexer.has("decimal") ? {type: "decimal"} : decimal), (lexer.has("ws") ? {type: "ws"} : ws), (lexer.has("multiplication") ? {type: "multiplication"} : multiplication), (lexer.has("ws") ? {type: "ws"} : ws), (lexer.has("decimal") ? {type: "decimal"} : decimal)], "postprocess": ([first, , , , second]) => parseFloat(first) * parseFloat(second)}
]
  , ParserStart: ""
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
```

**Comment by anonymoussprocket** [comment]
see #486
